env:
  max_steps:
    carbs.utils.LinearSpace:
      min: 10240
      max: 81920
      is_integer: True
      scale: 10000

train:
  total_timesteps:
    carbs.utils.LogSpace:
      min: 500_000_000
      max: 10_000_000_000
      is_integer: True
      scale: 100_000_000
  learning_rate:
    carbs.utils.LogSpace:
      min: 1.0e-5
      max: 1.0e-3
      scale: .05
  gamma:
    carbs.utils.LogitSpace:
      min: .5
      max: 1.0
      scale: .05
  gae_lambda:
    carbs.utils.LogitSpace:
      min: .5
      max: 1.0
      scale: .05
  ent_coef:
    carbs.utils.LogSpace:
      min: 1.0e-5
      max: 1.0e-1
      scale: .05
  vf_ent_coef:
    carbs.utils.LogSpace:
      min: 1.0e-5
      max: 1.0e-1
      scale: .05

rewards:
  baseline.ObjectRewardRequiredEventsMapIds:
    reward:
      event: 
        carbs.utils.LogSpace:
          min: 1.0e-3
          max: 10.0
          scale: 0.5
      seen_pokemon: 
        carbs.utils.LogSpace:
          min: 1.0e-3
          max: 10.0
          scale: 2.0
      caught_pokemon: 
        carbs.utils.LogSpace:
          min: 1.0e-3
          max: 10.0
          scale: 2.0
      moves_obtained: 
        carbs.utils.LogSpace:
          min: 1.0e-3
          max: 10.0
          scale: 2.0
      hm_count: 
        carbs.utils.LogSpace:
          min: 1.0e-3
          max: 10.0
          scale: 2.0
      level: 
        carbs.utils.LogSpace:
          min: 1.0e-5
          max: 10.0
          scale: 0.1
      badges: 
        carbs.utils.LogSpace:
          min: 1.0e-5
          max: 10.0
          scale: 2.0
      explore_hidden_objs: 
        carbs.utils.LogSpace:
          min: 1.0e-7
          max: 1.0
          scale: 1e-3
      explore_signs: 
        carbs.utils.LogSpace:
          min: 1.0e-4
          max: 1.0
          scale: 1e-3
      required_event: 
        carbs.utils.LogSpace:
          min: 1.0e-3
          max: 10.0
          scale: 2.0
      required_item: 
        carbs.utils.LogSpace:
          min: 1.0e-3
          max: 10.0
          scale: 2.0
      useful_item: 
        carbs.utils.LogSpace:
          min: 1.0e-3
          max: 10.0
          scale: 0.5
      pokecenter_heal: 
        carbs.utils.LogSpace:
          min: 1.0e-4
          max: 10.0
          scale: 0.1
      exploration: 
        carbs.utils.LogSpace:
          min: 1.0e-3
          max: 1.0
          scale: 0.01
      explore_warps: 
        carbs.utils.LogSpace:
          min: 1.0e-3
          max: 10.0
          scale: 0.005
      use_surf: 
        carbs.utils.LogSpace:
          min: 1.0e-3
          max: 2.0
          scale: 0.25
# policies:
#   multi_convolutional.MultiConvolutionalPolicy:
#     policy:
#       hidden_size:
#         carbs.utils.LinearSpace:
#           min: 512
#           max: 1024
#           is_integer: True

#     rnn:
#       # Assumed to be in the same module as the policy
#       name: MultiConvolutionalRNN
#       args:
#         input_size:
#           carbs.utils.LinearSpace:
#             min: 512
#             max: 2048
#             is_integer: True
#         hidden_size:
#           carbs.utils.LinearSpace:
#             min: 512
#             max: 2048
#             is_integer: True

